trigger:
- main  # Runs the pipeline when code is pushed to main branch
 
pool:
  vmImage: 'ubuntu-latest'  # Use Linux VM for better performance
 
steps:
# Step 1: Install Node.js
- task: UseNode@2
  inputs:
    version: '18.x'  # Change this to match your React app's Node.js version
 
# Step 2: Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'
 
# Step 3: Build the React App
- script: |
    npm run build
  displayName: 'Build React App'
 
# Step 4: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'build'  # React output folder
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'
has context menu