trigger:
  - main  # Runs when code is pushed to the main branch
 
pool:
  vmImage: 'ubuntu-latest'  # Use Linux VM for better performance
 
steps:
  # Step 1: Install Node.js manually
  - script: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      node -v
      npm -v
    displayName: 'Manually Install Node.js'
 
  # Step 2: Install dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'
 
  # Step 3: Build the React App
  - script: |
      npm run build
    displayName: 'Build React App'
 
  # Step 4: Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build'  # React output folder
      artifactName: 'drop'
    displayName: 'Publish Build Artifacts'